### PR TITLE
Add ByteDance Logo

### PR DESCRIPTION
**Pull request by XadillaX**

### CODE REVIEW

**Comment by jasnell** [comment]
@XadillaX ... this is great to see. With the PR, we also need some statement making it clear that we have permission from ByteDance to use the logo/trademark.

**Comment by XadillaX** [comment]
> @XadillaX ... this is great to see. With the PR, we also need some statement making it clear that we have permission from ByteDance to use the logo/trademark.

Sure, I've already passed our company's progress. Should I send that file to somewhere?

**Comment by jasnell** [comment]
Just copy / screenshot the relevant bits of the permission to this PR and that should work just fine.

**Comment by XadillaX** [comment]
I'm not sure that the content of permission is public or not. Should I paste it in this PR?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by lucacasonato** [comment]
> I'm not sure that the content of permission is public or not. Should I paste it in this PR? Or find a more private place to send?

Feel free to DM it to @jasnell  or me on Matrix if it is not public.

**Comment by XadillaX** [comment]
> > I'm not sure that the content of permission is public or not. Should I paste it in this PR? Or find a more private place to send?
> 
> Feel free to DM it to @jasnell or me on Matrix if it is not public.

Done. I've DM you the file on Matrix. Thanks.

**Review by lucacasonato — APPROVED** [review]
Thank you @XadillaX.

**Pull request merged**
